name: snake

on:
  schedule:
    - cron: "0 0 * * *" 
   
  push:
    branches:
      - main
      
jobs:
  build:
    name: Update snake images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    
    steps:
      
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Import GPG key
        run: echo $GPG_KEY | base64 --decode | gpg --batch --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}

      - name: Setup git environment
        run: |
          git config commit.gpgsign true
          git config user.signingkey $GPG_KEY_ID
          git config --global user.email "i+github@sunyz.net"
          git config --global user.name "realSunyz's GitHub Bot"
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/snake.svg
            snake/snake-dark.svg?palette=github-dark
      
      - name: Commit and push
        run: |-
          git diff
          git add snake/ && git commit -m "[±] Scheduled snake images update" || exit 0
          git pull && git push