name: wakatime

on:
  schedule:
    - cron: "0 12 * * *" 
   
  push:
    branches:
      - main

jobs:
  build:
    name: Update README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md

    steps:

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
        id: go

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Import GPG key
        run: echo $GPG_KEY | base64 --decode | gpg --batch --import
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        
      - name: Setup git environment
        run: |
          git config commit.gpgsign true
          git config user.signingkey $GPG_KEY_ID
          git config --global user.email "i+github@sunyz.net"
          git config --global user.name "realSunyz's GitHub Bot"
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Clone and run waka-box-go
        run: |-
          git clone https://github.com/realSunyz/waka-box-go.git
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/
          ./waka
      
      - name: Commit and push
        run: |-
          git diff
          git add README.md && git commit -m "[±] Scheduled waka-box-go update" || exit 0
          git pull && git push