name: wakatime

on:
  schedule:
    - cron: "0 0 * * *" 
   
  push:
    branches:
      - main

jobs:
  build:
    name: Update README.md
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
        id: go

      - name: Check out repo
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Clone and run waka-box
        run: |-
          git clone https://github.com/realSunyz/waka-box-go.git
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/
      - name: Commit and push
        run: |-
          ./waka
          git config --global user.email "bot@github.com" && git config --global user.name "Waka-Bot"
          git diff
          git add README.md && git commit -m "[±] Scheduled waka-box-go update" || exit 0
          git pull && git push